#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
#    url: jdbc:oracle:thin:@18.208.113.216:1521:XE
    username: hr
    password: hr


  #jpa
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      #jpa ddl-auto
      #create: DROP 후 CREATE
      #create-drop: DROP 후 CREATE 후 DROP, DML을 사용하지 않는 다면 DROP되지 않음
      #update: Entity와 DB 스키마 비교 후 수정 사항 반영(컬럼 추가)
      #validate: Entity와 DB 스키마 비교(다르면 예외 발생)
      ddl-auto: update

    #jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #log
  output:
    ansi:
      enabled: always

# 이미지 용량
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

      location: c:\\upload
      enabled: true

  #Redis
  session:
    store-type: redis

    #mail
    spring:
      mail:
      host: smtp.gmail.com
      port: 587
      username: 'official.dodamdodam@gmail.com'
      password: 'rvustqajqwshccam'
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true



  #OAuth2
  security:
    oauth2:
      client:
        registration:
          #naver
          naver:
            client-name: Naver
            client-id: LwN2FiWbr8qTUjRYPyjI
            client-secret: tQQOlIUsof
            redirect-uri: http://localhost:10000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,mobile

          #kakao
          kakao:
            client_name: kakao
            client-id: ef0f0e2124248605af3acf60b98886d2
            client-secret: 03wP4xJHpwKXPzBm6EaiKKDJc2lfCusP
            redirect-uri: http://localhost:10000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email

        provider:
          #naver
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          #kakao
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
